\NeedsTeXFormat{LaTeX2e}
\ProvidesClass{TC}[2016/11/12 TC]

%---------------------------------------%
% Class arranged by : Tsz Timmy Chan	%
%                 Date : Oct, 2016		%
%---------------------------------------%
\LoadClass{article}


\DeclareOption*{\PassOptionsToClass{\CurrentOption}{article}}
\ProcessOptions\relax

%page properties%
\hoffset=0in 
\voffset=-.5in
\oddsidemargin=0in
\evensidemargin=0in
\topmargin=0in 
\textwidth=6.5in
\textheight=9in



